import Head from 'next/head'
import Inicio from '../../components/Inicio'
import About from '../../components/About'
import Imagens from '../../components/Imagens'

export default function Home() {
  return (
    <>
      <Head>
        <title>Projeto React</title>
        <meta charSet="UTF-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Inicio />
        <About />
        <Imagens />
      </div>
    </>
  )
}
